#!/usr/bin/env python3
"""
fetch_recent_comments.py — pull the latest comments on giscus-backed posts
and write them to _data/recent_comments.yml so the Jekyll sidebar can render them.

How it works
------------
giscus stores each post's comments as a thread inside a GitHub Discussions
category. The discussion title is the post's pathname (because the giscus
mapping is `pathname` — see _config.yml). So:

    /ko/math/algebraic_structures/groups   -> discussion titled with that path
    /en/math/algebraic_structures/groups   -> separate discussion

We pull the most-recently-updated discussions and their newest comment,
look up the matching post in _site to grab its title, and partition by
the leading `/ko/` or `/en/` segment.

Setup
-----
1. Auth source: `gh auth token` (already logged in as math-jh with `repo`
   scope). Falls back to MATHJH_GH_TOKEN env var if gh is unavailable.
2. Make sure giscus is set up for math-jh/math-jh.github.io and the
   discussion category is configured in _config.yml under comments.giscus.
3. Add to crontab (suggested every 15 min):

       */15 * * * * cd /home/junhyeok/math-jh.github.io/scripts \\
                    && /usr/bin/python3 fetch_recent_comments.py >>fetch_comments.log 2>&1

Notes
-----
- ko ⇄ en separation is by URL prefix only; the Liquid include enforces it too.
- If the GraphQL query fails (rate limit, token missing), the script keeps
  the previous _data/recent_comments.yml untouched.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

BLOG_ROOT = Path("/home/junhyeok/math-jh.github.io")
DATA_PATH = BLOG_ROOT / "_data" / "recent_comments.yml"
REPO = "math-jh/math-jh.github.io"
DISCUSSION_LIMIT = 30  # how many recent discussions to scan
PER_LANG_LIMIT = 5     # how many comments to keep per language

GRAPHQL_QUERY = """
query($owner: String!, $name: String!, $first: Int!) {
  repository(owner: $owner, name: $name) {
    discussions(first: $first, orderBy: {field: UPDATED_AT, direction: DESC}) {
      nodes {
        title
        url
        updatedAt
        comments(last: 1) {
          nodes {
            bodyText
            url
            createdAt
            author { login }
          }
        }
      }
    }
  }
}
"""


def _load_token() -> str | None:
    token = os.environ.get("MATHJH_GH_TOKEN")
    if token:
        return token.strip()
    gh = shutil.which("gh")
    if gh:
        try:
            r = subprocess.run([gh, "auth", "token"], capture_output=True, text=True, timeout=10)
            if r.returncode == 0 and r.stdout.strip():
                return r.stdout.strip()
        except (OSError, subprocess.SubprocessError):
            pass
    return None


def _gql(token: str) -> dict[str, Any]:
    owner, name = REPO.split("/", 1)
    payload = json.dumps({
        "query": GRAPHQL_QUERY,
        "variables": {"owner": owner, "name": name, "first": DISCUSSION_LIMIT},
    }).encode()
    req = urllib.request.Request(
        "https://api.github.com/graphql",
        data=payload,
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "math-jh-recent-comments/1",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def _lang_of(pathname: str) -> str | None:
    if pathname.startswith("/ko/"):
        return "ko"
    if pathname.startswith("/en/"):
        return "en"
    return None


def _yaml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _emit_yaml(by_lang: dict[str, list[dict[str, str]]]) -> str:
    out: list[str] = [
        "# Auto-generated by scripts/fetch_recent_comments.py.",
        "# Do not edit by hand; the next cron run will overwrite this file.",
    ]
    for lang in ("ko", "en"):
        entries = by_lang.get(lang, [])
        if not entries:
            out.append(f"{lang}: []")
            continue
        out.append(f"{lang}:")
        for e in entries:
            out.append(f"  - permalink: \"{_yaml_escape(e['permalink'])}\"")
            out.append(f"    title:     \"{_yaml_escape(e['title'])}\"")
            out.append(f"    author:    \"{_yaml_escape(e['author'])}\"")
            out.append(f"    updated:   \"{_yaml_escape(e['updated'])}\"")
            out.append(f"    anchor:    \"giscus-comments\"")
    return "\n".join(out) + "\n"


def _post_title_for(pathname: str) -> str:
    """Best-effort post-title lookup from _posts frontmatter via the rendered site."""
    # Quick path: look at the _site index if it's been built.
    site_path = BLOG_ROOT / "_site" / pathname.lstrip("/") / "index.html"
    if site_path.exists():
        try:
            head = site_path.read_text(errors="ignore")[:4096]
            # MM puts the title inside <title>...</title>
            start = head.find("<title>")
            end = head.find("</title>")
            if start != -1 and end != -1:
                title = head[start + 7:end].strip()
                # MM appends " - Site title"; trim the suffix.
                for sep in (" - ", " | "):
                    if sep in title:
                        title = title.split(sep, 1)[0].strip()
                        break
                if title:
                    return title
        except OSError:
            pass
    return pathname.rsplit("/", 1)[-1].replace("_", " ").replace("-", " ").title()


def main() -> int:
    token = _load_token()
    if not token:
        print("error: no GitHub token. Run `gh auth login` or set MATHJH_GH_TOKEN.", file=sys.stderr)
        return 2

    try:
        data = _gql(token)
    except urllib.error.HTTPError as e:
        print(f"error: GitHub API HTTP {e.code}: {e.read()[:200].decode(errors='ignore')}", file=sys.stderr)
        return 3
    except (urllib.error.URLError, TimeoutError) as e:
        print(f"error: GitHub API request failed: {e}", file=sys.stderr)
        return 3

    if "errors" in data:
        print(f"error: GraphQL errors: {data['errors']}", file=sys.stderr)
        return 4

    discussions = (data.get("data") or {}).get("repository", {}).get("discussions", {}).get("nodes", [])
    by_lang: dict[str, list[dict[str, str]]] = {"ko": [], "en": []}

    for d in discussions:
        pathname = (d.get("title") or "").strip()
        if not pathname.startswith("/"):
            continue
        lang = _lang_of(pathname)
        if not lang:
            continue
        comments = (d.get("comments") or {}).get("nodes") or []
        if not comments:
            continue
        c = comments[-1]
        if len(by_lang[lang]) >= PER_LANG_LIMIT:
            continue
        by_lang[lang].append({
            "permalink": pathname,
            "title": _post_title_for(pathname),
            "author": (c.get("author") or {}).get("login", "anon"),
            "updated": c.get("createdAt", ""),
        })

    DATA_PATH.write_text(_emit_yaml(by_lang), encoding="utf-8")
    total = sum(len(v) for v in by_lang.values())
    print(f"wrote {total} recent comments to {DATA_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
